codestates-seb/seb44_main_018

client/src/pages/copyPopUp/CopyPopUp.tsx, client/src/pages/feedEditing/FeedEditing.tsx, client/src/pages/feedPopUp/FeedPopUp.tsx, client/src/pages/feedPosting/FeedPosting.tsx, client/src/pages/home/Home.tsx, client/src/pages/info/Info.tsx, client/src/pages/infoEditing/InfoEditing.tsx, client/src/pages/login/Login.tsx, client/src/pages/myPage/MyPage.tsx, client/src/pages/notFound/NotFound.tsx, client/src/pages/userpage/UserPage.tsx, client/src/pages/walkEditing/WalkEditing.tsx, client/src/pages/walkFeed/WalkFeed.tsx, client/src/pages/walkMate/WalkMate.tsx, client/src/pages/walkPosting/WalkPosting.tsx, client/src/routers/paths.ts, client/src/routers/routers.tsx
- enum으로 지정해두었던 경로들을 createBrowserRouter를 사용하여 라우팅을 설정하였습니다.
- pages에 각 경로별 페이지를 구성하였습니다.
- 생성이슈는 없습니다.
=> Feat: 라우터 경로 설정 및 페이지 설정

client/src/common/select/Select.tsx, client/src/hook/useZipCode.tsx, client/src/pages/info/Info.tsx
https://github.com/codestates-seb/seb44_main_018/assets/57277708/7843dbf9-2e9a-44b3-a8a6-9cc247a67307
- 무작위로 주소 선택시 page 에러 해결
- 첫 번째 고정된 값, 서울 특별시를 받아오도록 수정
- info page에서 주소 값을 가지고 올 수 있도록 수정
- 읍,면,동 선택 후 광역시, 도 변경시, 읍,면 데이터가 남아있는 버그 수정
=> Fix: Select Component 오류 수정

client/src/api/mutationfn.ts, client/src/api/queryfn.ts, client/src/api/url.ts, client/src/components/subscribe/Subscribe.tsx, client/src/components/subscribe/subscribe.styled.tsx, client/src/pages/myPage/MyPage.tsx, client/src/pages/myPage/myPage.styled.tsx, client/src/pages/userpage/UserPage.tsx, client/src/pages/userpage/userPage.styled.tsx, client/src/types/subscribe.ts, client/src/types/userType.ts
- #35 작업의 일부 완료
- 유저 프로필, 유저 네임, 구독여부 확인하여 볼 수 있도록 작성
- 유저가 반려동물을 등록했다면, 확인할 수 있도록 수정 
- 해당 유저가 팔로잉한 유저 리스트를 구독 클릭시 확인 가능 
- API 테스트를 추가적으로 진행해야 합니다.
=> Feat: user page 일부 작성

client/src/api/mutationfn.ts, client/src/pages/info/Info.tsx
- 주소, 닉네임 입력 후, 로그인 기능 구현 완료했습니다.
=> Refactor: 로그인 구현 완료

client/package-lock.json, client/package.json, client/src/api/queryfn.ts, client/src/api/url.ts, client/src/common/select/select.styled.tsx, client/src/pages/walkMate/WalkMate.styled.tsx, client/src/pages/walkMate/WalkMate.tsx, client/src/types/walkType.ts
- 서버 데이터를 받아오기 위해서 useinfinteQuery 일부 구현하였습니다. (무한 스크롤 로직은 추후 구현 예정입니다.)
- 반응형을 구현하기 위해 flex-direction을 row -> column으로 변경하였습니다. 
-
=> Feat: Walkmate 컴포넌트 서버 데이터 일부 구현

.gitignore, client/src/api/mutationfn.ts, client/src/pages/info/Info.tsx, client/src/pages/infoEditing/InfoEditing.tsx
- 회원 가입 및 회원 수정 코드를 한 파일에서 구현하고 있어, 사용하지 않는 코드들을 삭제하였습니다.
- 이슈 close
- close #80
=> Remove: 사용하지 않는 코드 및 파일 삭제

client/src/api/mutationfn.ts, client/src/components/pet/PetInfo.tsx, client/src/components/user_my_page/pet-container/PetContainer.tsx, client/src/pages/myPage/MyPage.tsx
- my page에 펫 등록, 수정, 삭제, 프로필 변경 시 실시간으로 반영되도록 수정
- my page 프로필 변경 API 추가
- my page 펫 수정 API 추가
- my apge 펫 삭제 API 추가
- #29 
https://github.com/codestates-seb/seb44_main_018/assets/57277708/1ddd7ab8-6ecd-4398-a81a-0c3c5f447e0f
=> Fix : my page 수정

client/src/components/card/sidenav/SideNav.tsx, client/src/pages/home/Home.tsx, client/src/pages/info/Info.tsx
- accessToken이 필요한 API와 필요하지 않는 코드들로 분리하였습니다.
=> Refactor: API 코드 전면 수정

client/src/App.tsx, client/src/api/url.ts, client/src/common/comment/Comment.tsx, client/src/common/header/Header.tsx, client/src/common/popup/popup.styled.tsx, client/src/components/card/feedCard/FeedCard.tsx, client/src/components/card/feedwritecard/FeedWriteCard.tsx, client/src/components/card/sidenav/SideNav.tsx, client/src/components/map/Map.tsx, client/src/components/pet/PetInfo.tsx, client/src/components/subscribe/Subscribe.tsx, client/src/components/user_my_page/pet-container/PetContainer.tsx, client/src/pages/feedPopUp/FeedPopUp.tsx, client/src/pages/home/Home.tsx, client/src/pages/info/Info.tsx, client/src/pages/myPage/MyPage.tsx, client/src/pages/userpage/UserPage.tsx, client/src/pages/walkFeed/WalkFeed.tsx, client/src/pages/walkMate/WalkMate.tsx
- SERVER_URL 수정하여 PR하였습니다.
- 아직 피드 팝업페이지 구현 중이지만, 브렌치 업데이트를 위해 PR하였습니다.
=> Feat&Fix: SERVER_URL 수정 및 피드 팝업페이지 구현중

client/src/api/mutationfn.ts, client/src/pages/walkEditing/WalkEditing.tsx
What is this PR?
- 산책 페이지 수정 api patch 로 수정
- 산책 페이지의 input 벨류를 수정할 수 있도록 변경
- close #40 
Todo
=> Fix: 산책 페이지 수정

client/src/common/header/Header.tsx, client/src/common/select/Select.tsx, client/src/pages/home/Home.tsx, client/src/pages/walkMate/WalkMate.tsx
https://github.com/codestates-seb/seb44_main_018/assets/57277708/4bd0ac64-0f27-49e7-be31-713d74cd2130
- useInfiniteQuery를 활용한 무한 스크롤을 구현했습니다.
=> Feat: useInfiniteQuery를 활용한 무한 스크롤 구현

client/src/components/notice/NoticeOnlyOwner.tsx, client/src/pages/myPage/myPage.styled.tsx
- 마이 페이지 버튼 및 마진 스타일을 수정하였습니다.
- 마이 페이지 버튼 및 마진 스타일을 수정하였습니다.
- 탭메뉴와의 마진수정
- 자신의 페이지일경우, 마이펫 등록 버튼 삭제
- 푸터와의 마진 수정
enshot
=> Style: mypage 페이지 스타일 수정

client/src/common/select/Select.tsx, client/src/pages/walkMate/WalkMate.tsx
- 광역시만 서버로 요청을 보낼때, 양 옆 공백에 의해서 데이터를 받아오지 못했습니다.
https://github.com/codestates-seb/seb44_main_018/assets/57277708/8db23c0b-f12f-497f-8ade-f66754573884
=> Fix: 무한 스크롤 버그 수정

client/src/common/button/Button.tsx, client/src/common/comment/Comment.tsx, client/src/common/comment/feedComment.tsx/FeedComment.tsx, client/src/components/follow-list/FollowList.tsx, client/src/components/pet/PetInfo.tsx, client/src/pages/feedPopUp/FeedPopUp.tsx, client/src/pages/userpage/UserPage.tsx, client/src/pages/walkEditing/WalkEditing.tsx, client/src/pages/walkFeed/WalkFeed.tsx, client/src/pages/walkMate/WalkMate.tsx, client/src/pages/walkPosting/WalkPosting.tsx, client/src/util/changeDateFormat.ts, client/src/util/changeTiem.ts
- walk 게시물 댓글 프로필 클릭시 userpage 이동하게 수정
- 유저페이지에서 구독리스트를 통해 다른 유저에게 이동시 followList가 열려있는 채로 이동되는 버그 수정
- 서버에서 WTC 시간 기준으로 주기 때문에 한국 시간을 고려해서 수정
- 서버에서 주는 시간에 +9 하여 생성
- 팝업 메시지에 유저에게 필요한 설명이 포함되도록 수정
- 펫 등록 버튼을 빠르게 여러번 클릭시 중복 등록 되는 버그 수정
- 펫 나이 제한 생성(0~100)
- 펫 성별 등록 필수 요소로 변경
- 펫의 이름에 공백과 특수문자 불가하게 수정
- 오픈 채팅방 링크 작성시 반드시 http://, https://로 시작하게 작성
- 최대 산책 동반 반려동물의 수는 101마리로 제한
- WalkCard 컴포넌트 날짜 형식 수정
- util/changeDateFormat 활용
=> Fix: 산책페이지, 댓글페이지 수정

client/src/common/input/Input.styled.tsx, client/src/pages/info/Info.styled.tsx, client/src/pages/info/Info.tsx, client/src/pages/myPage/MyPage.tsx, client/src/pages/walkMate/WalkMate.tsx, client/src/pages/walkPosting/WalkPosting.tsx
- 유저 정보를 수정하는 infoEditing 페이지에서 기존 disabled를 제거하고, 닉네임을 변경할 수 있도록 수정하였습니다. 
- 산책페이지에서 모집완료와 모집중 모두를 볼 수 있는 전체보기와 모집중인 게시글만 볼 수 있는 모집중 필터링 버튼을 만들었습니다. 
- 코드 내 console.log를 삭제하였습니다.
=> Fix: 닉네임 변경 로직 구현 & 산책페이지 필터 버튼 구현

client/src/pages/myPage/MyPage.tsx, client/src/pages/userpage/UserPage.tsx, client/src/types/userType.ts
- 유저페이지 피드게시물 무한스크롤 구현 완료하였습니다.
- 탭 스타일을 수정하였습니다.
=> Refactor&Style: 유저페이지 피드게시물 무한스크롤 구현

client/src/App.tsx
- 마이페이지, 산책 페이지 이동시 스크롤 상단에 고정되도록 수정
- react-router-dom 의 ScrollRestoration 활용 [링크](https://reactrouter.com/en/main/components/scroll-restoration) -
=> [FE][Fix]: 스크롤 고정

client/src/api/queryfn.ts, client/src/pages/home/Home.tsx
=> [FE][Feat]: 홈 무한 페이지 구현

client/src/api/mutationfn.ts, client/src/common/header/Header.styled.tsx, client/src/pages/info/Info.tsx, client/src/pages/myPage/MyPage.tsx, client/src/pages/myPage/myPage.styled.tsx, client/src/pages/userpage/UserPage.tsx
- 마이페이지에서 보여지는 댓글 리스트 CSS를 수정하였습니다. 
- 모바일 뷰에서 피드리스트 사이즈를 수정하였습니다. 
- 회원탈퇴 로직을 일부 구현하였습니다. (서버 에러로인해 추가 구현 필요)
=> Feat & Refactor: 회원탈퇴기능 & 마이페이지 댓글 리스트 CSS 수정

client/src/components/nav/NavBar.tsx
- NavBar 렌더링 시, 양쪽 여백 padding 수정하였습니다.
=> Style: NavBar  스타일 수정

client/src/components/follow-list/followList.styled.tsx, client/src/components/map-make/Map.tsx, client/src/pages/walkMate/WalkMate.tsx, client/src/pages/walkPosting/WalkPosting.tsx
- 초기 카카오맵 위치 세팅시에, 유저 주소를 바탕으로 위치를 결정할시 버그가 발생
- 이후 마커 생성에서 마우스 클릭과 다른 위치에 마커가 생성되는 문제가 발생
-  따라서 카카오 맵 초기 위치를 모든 유저가 같게 하도록 재설정
=> [FE][Fix]: 카카오 맵 수정 

client/src/components/card/sidenav/SideNav.tsx, client/src/pages/feedPopUp/FeedPopUp.styled.tsx, client/src/pages/feedPopUp/FeedPopUp.tsx
- 배포환경에서 알림토스트가 보이지 않는 에러를 수정하였습니다.
- 이외에도 피드팝업 스타일을 수정하였습니다.
=> Refactor&Style: 배포환경 알림토스트 에러 수정

client/netlify.toml, client/src/api/url.ts
- netlify로 배포하기 위해 proxy설정을 하여 코드를 수정하였습니다.
- localhost환경 서버인지 여부에 따라 proxy설정 분기처리 하였습니다.
=> Refactor: proxy 설정으로 인한 netlify 설정 파일 추가 

client/netlify.toml
- 요청이 제대로 가지않아 ':splat' 코드를 추가하였습니다.
=> Refactor: netlify.toml 파일 수정

client/index.html, client/src/api/url.ts
- url.ts 파일 수정하였습니다. 이외에 index.html 오타 수정하였습니다.
=> Fix: 배포 및 코드 수정

client/src/api/url.ts, client/sw.ts, client/vite.config.ts
What is this PR?
- vite proxy 설정
- vite.config.ts proxy server 설정
Todo
=> Feat: vite proxy 설정

client/src/assets/button/write.svg, client/src/common/comment/Comment.tsx, client/src/common/comment/comment.styled.tsx, client/src/pages/walkFeed/WalkFeed.tsx
- 공백만 입력했을 경우 버튼을 비활성화 처리하였습니다.
=> Refactor: 댓글 수정, 삭제 텍스트 공백일 때 비활성화 처리

client/index.html, client/src/common/comment/Comment.tsx, client/src/common/popup/Popup.tsx, client/src/common/popup/popup.styled.tsx, client/src/common/select/Select.tsx, client/src/components/map-make/Map.tsx, client/src/components/user_my_page/pet-container/PetContainer.tsx, client/src/main.tsx, client/src/pages/myPage/MyPage.tsx, client/src/pages/userpage/UserPage.tsx, client/src/pages/walkFeed/WalkFeed.tsx
- Select 에서 구 선택 후 선택 변경시 검색 불가 오류 수정
- 지도를 안 건드리면 지도가 나타나지 않는 현상 수정, 유저가 선책한 주소 위치에서 카카오 맵 시작하도록 수정
- 모든 mutation(post, delete, patch)를 실패했을 떄, 실패를 유저에게 알리는 팝업창 설정 (유저페이지, 마이페이지, 산책 생성, 수정, 산책 페이지)
- 버튼에 커서 작업이 안 되어 있는 것 커서 작업
=>  [FE][Fix]: 지도, Select 수정, 팝업 수정

client/src/pages/userpage/UserPage.tsx
=> Remove: lint 에러 수정

client/src/common/comment/Comment.tsx, client/src/common/input/Input.styled.tsx, client/src/pages/walkMate/WalkMate.tsx, client/src/pages/walkPosting/WalkPosting.tsx
- 데이터를 불러오는 과정에서 에러가 발생하면 에러 컴포넌트를 렌더링합니다. 
- 모바일 뷰 변경 시, 에러 메세지와 labelText가 겹치는 부분을 수정하였습니다.
=> Feat: 산책 게시물 페이지 에러처리 추가

client/src/components/card/feedwritecard/FeedWriteCard.tsx, client/src/components/user_my_page/pet-container/PetContainer.tsx
- svg파일에 stroke를 주지 않아 삭제 버튼이 보이지 않는 에러를 수정하였습니다.
=> Fix&Style: 삭제 보이지 않는 에러 수정

client/src/components/card/sidenav/SideNav.tsx, client/src/pages/feedPopUp/FeedPopUp.tsx, client/src/pages/userpage/UserPage.tsx
- accessToken의 여부에 따라 공유 게시물이 다르게 보이게 설정하였습니다.
=> Refactor: 공유 게시물 보일때 피드 게시물 팝업

client/src/pages/home/Home.tsx
=> Remove: lint 에러 코드 삭제

client/src/pages/loading/Loading.tsx
- searchParams가 뭔지 콘솔에 찍어보았습니다.
=> Test: console.log - searchParams

client/src/pages/loading/Loading.tsx
- setAccessToken를 사파리에서도 인식을 하는지 콘솔에 찍어보았습니다.
=> Test: console.log - setAccessToken

client/src/pages/loading/Loading.tsx
- 조건을 searchParams.size !== 0일 때 로컬스토리지에 정상적으로 저장되는 것 확인 후, 콘솔 삭제했습니다.
=> Test: console.log 삭제

client/src/pages/loading/Loading.tsx
- loading component에서 firstVisited 삭제하였습니다.
=> Refactor: firstVisited 삭제

client/src/pages/login/Login.tsx
- firstVisited를 null로 초기화하고 null 일때만 true로 바뀔 수 있도록 수정하였습니다.
=> Refactor: firstVisited 저장 로직 수정

client/src/pages/login/Login.tsx
- firstVisited 값을 저장하는 방법을 수정하였습니다.
=> Refactor: firstVisited 초기화 수정

client/src/pages/loading/Loading.tsx, client/src/pages/login/Login.tsx
=> Fix: 웰컴팝업이 계속 뜨는 오류 수정

client/index.html, client/src/components/card/feedwritecard/FeedWriteCard.tsx, client/src/components/card/sidenav/SideNav.tsx, client/src/components/pet/petProfile/PetProfile.tsx, client/sw.js
- 피드 게시물 및 피드 팝업에서 일어나는 에러들을 수정하였습니다.
- 반려동물 팝업 스타일 수정하였습니다.
=> Fix&Style: 피드 게시물, 피드팝업 수정

client/src/pages/feedPopUp/FeedPopUp.tsx, client/src/pages/home/Home.tsx
- Home.page staleTime을 추가하였습니다.
=> Refactor&Remove: query staleTime 추가

client/src/pages/walkMate/WalkMate.tsx
- 산책 게시글 페이지 모집중 카드컴포넌트 시간 형식 수정하였습니다.
=> Refactor: 산책 게시글 페이지 모집중 카드컴포넌트 시간 수정

client/src/components/card/feed-card/FeedCard.styled.tsx, client/src/components/card/sidenav/SideNav.tsx, client/src/pages/feedPopUp/FeedPopUp.styled.tsx, client/src/pages/home/Home.styled.tsx, client/src/pages/home/Home.tsx
- 사이드 네브바 에러가 있어 수정하였습니다.
- 게스트 로그인시 알림토스트가 보이지 않는 에러가 있어서 수정하였습니다.
=> Refactor&Fix: 피드 리스트, 팝업 네브바 에러 수정

client/src/pages/feedPopUp/FeedPopUp.tsx
=> Remove: 알림 토스트 관련 코드 제거

client/netlify.toml, client/src/api/url.ts, client/vite.config.ts
- https 환경에서도 정상적으로 동작하는지 확인하기 위한 테스트로, proxy 서버를 수정하였습니다.
=> Test: proxy 서버 https환경 테스트

client/netlify.toml
- netlify.toml 내 redirects 코드 제거하였습니다.
=> Test: netlify.toml 내 redirects 코드 제거

client/public/_redirects
=> Test: _redirects 코드 추가

client/netlify.toml, client/public/_redirects
=> Test: _redirects 코드 삭제

client/netlify.toml, client/public/_redirects
- _redirects 코드 public으로 이동하였습니다.
=> Test: _redirects 코드 public으로 이동

client/netlify.toml, client/public/_redirects
-  _redirects 코드 public으로 이동(api코드까지 이동하였습니다.)
=> Test: _redirects 코드 public으로 이동(api코드까지 이동)

client/src/components/pet/PetInfo.tsx, client/src/components/pet/petInfo.styled.tsx
- 팝업창의 백그라운드를 클릭 해도 닫히지 않도록 수정
=> Fix: PetPopUP 수정

client/src/pages/info/Info.tsx
- 회원정보 수정 페이지에서 뒤로갈 수 있는 뒤로가기 버튼을 추가하였습니다.
=> Fix: 회원정보 뒤로가기 버튼 추가

client/src/pages/walkEditing/WalkEditing.tsx
- 산책 글쓰기 수정페이지에서 X 버튼 클릭 시, 이전페이지로 이동하도록 수정하였습니다.
=> Fix: 산책글쓰기 수정페이지 X버튼 클릭 시, 이전페이지로 이동

client/src/components/card/walk-card/walkCard.styled.tsx, client/src/pages/walkMate/WalkMate.tsx
=> Style: Walkmate Grid 스타일 수정

client/src/pages/home/Home.tsx
What is this PR?
- refetch로 인한 데이터 재불러오기로 인한 중복 제거
=> Fix: home 무한 스크롤 수정

client/src/pages/home/Home.tsx
- 새로고침시 데이터가 유지되는 상황을 수정하였습니다.
=> Fix: 새로고침시, 데이터 유지되는 상황 수정
